In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
import numpy as np
from sklearn.model_selection import train_test_split
from collections import Counter


In [2]:
x_train = np.load('../../not_editable/balance_300/x_train.npy')
y_train = np.load('../../not_editable/balance_300/y_train.npy')

x_test = np.load('../../not_editable/balance_300/x_test.npy')
y_test = np.load('../../not_editable/balance_300/y_test.npy')

In [3]:
x_train = x_train.tolist()
y_train = y_train .tolist()
x_test = x_test.tolist()
y_test = y_test .tolist()

In [4]:
#train size 
print len(x_train)
print len(y_train)
#test size 
print len(x_test)
print len(y_test)

47960
47960
20555
20555


In [7]:
def output_result(solver, hidden_layer,learning_method,tol  ):
    clf = MLPClassifier(solver=solver, hidden_layer_sizes=hidden_layer,
                        learning_rate=learning_method,max_iter = 400,tol= tol)
    clf.fit(x_train, y_train)    
    train_fited = clf.predict(x_train)
    train_confusion_matrix = confusion_matrix(y_train, train_fited)
    train_acc = (sum(np.diag(train_confusion_matrix))+0.0)/sum(sum(train_confusion_matrix))
    print 'on balanced data:'
    print 'training acc:'
    print train_acc
    print train_confusion_matrix
    #test
    test_predicted = clf.predict(x_test)
    test_confusion_matrix = confusion_matrix(y_test,test_predicted )
    test_acc = (sum(np.diag(test_confusion_matrix))+0.0)/sum(sum(test_confusion_matrix))
    print 'testing acc:'
    print test_acc
    print test_confusion_matrix
    
    return([train_acc,test_acc])

In [12]:
## when using sgd, learning mathod adaptive, max iteration 400, learning rate 1e-5 , 
solver= 'adam';learning_method  = 'adaptive'
hidden_layer = [20,20]
acc_results = []
tols = [1e-2,1e-3,1e-4,1e-5,1e-6,1e-7]
for tol in tols : 
    print tol
    acc_results.append(output_result(solver, hidden_layer,learning_method ,tol))
acc_results

0.01
on balanced data:
training acc:
0.476563803169
[[6143 1915  549  293  692]
 [2162 3244 2540 1032  614]
 [ 686 1881 3845 2507  673]
 [ 356  825 2160 4044 2207]
 [ 638  435  654 2285 5580]]
testing acc:
0.47603989297
[[2646  810  246  126  283]
 [ 926 1356 1112  447  270]
 [ 304  778 1628 1100  301]
 [ 136  383  979 1697  916]
 [ 287  194  229  943 2458]]
0.001
on balanced data:
training acc:
0.502481234362
[[6180 2158  518  210  526]
 [1919 3856 2563  711  543]
 [ 565 2141 4311 1901  674]
 [ 284  880 2453 3703 2272]
 [ 480  445  692 1926 6049]]
testing acc:
0.495548528339
[[2648  915  227   76  245]
 [ 847 1596 1110  315  243]
 [ 251  935 1787  848  290]
 [ 119  405 1076 1558  953]
 [ 233  203  254  824 2597]]
0.0001
on balanced data:
training acc:
0.503711426188
[[6689 2043  378  130  352]
 [2342 4139 2137  570  404]
 [ 725 2635 3959 1715  558]
 [ 386 1153 2373 3559 2121]
 [ 637  529  692 1922 5812]]
testing acc:
0.496083677937
[[2853  843  170   69  176]
 [1024 1741  903  255  18

[[0.47656380316930774, 0.47603989297008026],
 [0.50248123436196834, 0.49554852833860374],
 [0.50371142618849041, 0.49608367793724156],
 [0.50510842368640529, 0.49579177815616637],
 [0.50907005838198494, 0.49997567501824375],
 [0.50717264386989158, 0.4991972756020433]]

In [13]:
solver= 'adam';learning_method  = 'constant'
hidden_layer = [20,20]
acc_results = []
tols = [1e-2,1e-3,1e-4,1e-5,1e-6,1e-7]
for tol in tols : 
    print tol
    acc_results.append(output_result(solver, hidden_layer,learning_method ,tol))
acc_results

0.01
on balanced data:
training acc:
0.476709758132
[[6040 2142  471  296  643]
 [2071 3588 2344 1034  555]
 [ 644 2147 3607 2569  625]
 [ 331  988 2003 4209 2061]
 [ 585  530  605 2453 5419]]
testing acc:
0.4750668937
[[2601  909  212  122  267]
 [ 895 1489 1029  452  246]
 [ 280  891 1529 1111  300]
 [ 127  451  903 1779  851]
 [ 263  218  221 1042 2367]]
0.001
on balanced data:
training acc:
0.502773144287
[[6558 1728  468  285  553]
 [2220 3357 2426 1003  586]
 [ 694 1863 3841 2537  657]
 [ 334  742 1936 4292 2288]
 [ 531  355  520 2121 6065]]
testing acc:
0.495062028703
[[2793  724  213  123  258]
 [ 978 1380 1038  438  277]
 [ 304  795 1590 1112  310]
 [ 150  320  883 1799  959]
 [ 267  144  187  899 2614]]
0.0001
on balanced data:
training acc:
0.508110925771
[[6791 1782  426  191  402]
 [2384 3780 2304  664  460]
 [ 790 2230 4076 1901  595]
 [ 410  924 2280 3837 2141]
 [ 599  448  659 2001 5885]]
testing acc:
0.496229627828
[[2878  768  195   89  181]
 [1057 1549 1000  297  208

[[0.47670975813177646, 0.47506689369982974],
 [0.50277314428690578, 0.49506202870347848],
 [0.50811092577147621, 0.49622962782777913],
 [0.51201000834028354, 0.50002432498175631],
 [0.51184320266889072, 0.49540257844806618],
 [0.5065679733110926, 0.49618097786426663]]

In [82]:
solver = 'adam'
learning_method = 'constant'
hidder_layers = [[5,5],[5,5,5],[5,5,5,5],[5,5,5,5,5],[5,5,5,5,5,5],
                 [10,10],[10,10,10],[10,10,10,10],[10,10,10,10,10],[10,10,10,10,10,10],
                 [15,15],[15,15,15],[15,15,15,15],[15,15,15,15,15],[15,15,15,15,15,15],
                 [20,20],[20,20,20],[20,20,20,20],[20,20,20,20,20],[20,20,20,20,20,20],]
acc_results = []
for hidden_layer in hidder_layers: 
    print hidden_layer 
    acc_results.append(output_result(solver, hidden_layer,learning_method  ))
acc_results

[5, 5]
on balanced data:
training acc:
0.494641367807
[[6655 1822  384  185  546]
 [2421 3575 2217  778  601]
 [ 779 2177 3771 2132  733]
 [ 384  923 2122 3674 2489]
 [ 634  440  589 1881 6048]]
testing acc:
0.494234979324
[[2849  773  177   74  238]
 [1057 1481  977  338  258]
 [ 334  934 1608  915  320]
 [ 164  400  955 1561 1031]
 [ 303  176  202  770 2660]]
[5, 5, 5]
on balanced data:
training acc:
0.2
[[   0    0    0    0 9592]
 [   0    0    0    0 9592]
 [   0    0    0    0 9592]
 [   0    0    0    0 9592]
 [   0    0    0    0 9592]]
testing acc:
0.2
[[   0    0    0    0 4111]
 [   0    0    0    0 4111]
 [   0    0    0    0 4111]
 [   0    0    0    0 4111]
 [   0    0    0    0 4111]]
[5, 5, 5, 5]
on balanced data:
training acc:
0.48740617181
[[6394 1870  444  236  648]
 [2282 3269 2480  935  626]
 [ 690 1990 3796 2405  711]
 [ 322  848 2030 4009 2383]
 [ 545  425  552 2162 5908]]
testing acc:
0.486110435417
[[2753  771  206  110  271]
 [ 992 1373 1064  394  288]
 [ 293 

[[0.49464136780650542, 0.49423497932376553],
 [0.20000000000000001, 0.20000000000000001],
 [0.48740617180984153, 0.48611043541717341],
 [0.39678899082568808, 0.39766480175139868],
 [0.48544620517097581, 0.48289953782534661],
 [0.49466221851542952, 0.49014838238871322],
 [0.4908673894912427, 0.48761858428606181],
 [0.49716430358632191, 0.49389442957917784],
 [0.49614261884904087, 0.48781318414011188],
 [0.49412010008340285, 0.49175383118462662],
 [0.50235613010842373, 0.496035027973729],
 [0.50510842368640529, 0.49622962782777913],
 [0.49703919933277729, 0.48966188275358796],
 [0.49593411175979984, 0.49399172950620285],
 [0.49537114261884901, 0.49029433227925079],
 [0.51376146788990829, 0.49773777669666747],
 [0.5021893244370309, 0.49715397713451714],
 [0.5021684737281068, 0.49394307954269034],
 [0.50742285237698082, 0.49929457552906836],
 [0.50089658048373642, 0.49481877888591586]]

In [83]:
solver = 'adam'
learning_method = 'adaptive'
hidder_layers = [[5,5],[5,5,5],[5,5,5,5],[5,5,5,5,5],[5,5,5,5,5,5],
                 [10,10],[10,10,10],[10,10,10,10],[10,10,10,10,10],[10,10,10,10,10,10],
                 [15,15],[15,15,15],[15,15,15,15],[15,15,15,15,15],[15,15,15,15,15,15],
                 [20,20],[20,20,20],[20,20,20,20],[20,20,20,20,20],[20,20,20,20,20,20],]
acc_results = []
for hidden_layer in hidder_layers: 
    print hidden_layer 
    acc_results.append(output_result(solver, hidden_layer,learning_method  ))
acc_results

[5, 5]
on balanced data:
training acc:
0.493077564637
[[6676 1799  395  185  537]
 [2470 3436 2292  790  604]
 [ 757 2170 3784 2177  704]
 [ 366  893 2159 3848 2326]
 [ 607  434  622 2025 5904]]
testing acc:
0.49126733155
[[2839  764  174   90  244]
 [1064 1443 1003  343  258]
 [ 327  918 1605  925  336]
 [ 156  374  978 1626  977]
 [ 287  178  215  846 2585]]
[5, 5, 5]
on balanced data:
training acc:
0.491576313595
[[6479 1982  383  233  515]
 [2323 3636 2182  904  547]
 [ 707 2283 3577 2348  677]
 [ 328  929 1979 4020 2336]
 [ 561  490  564 2113 5864]]
testing acc:
0.490099732425
[[2760  841  178   99  233]
 [1005 1526  948  391  241]
 [ 317  961 1510 1020  303]
 [ 129  413  895 1716  958]
 [ 262  208  204  875 2562]]
[5, 5, 5, 5]
on balanced data:
training acc:
0.493473728107
[[6848 1757  429  129  429]
 [2609 3389 2501  576  517]
 [ 821 2144 4260 1738  629]
 [ 418  923 2630 3360 2261]
 [ 724  498  780 1780 5810]]
testing acc:
0.491170031622
[[2906  761  194   60  190]
 [1121 1430 1

[[0.49307756463719765, 0.49126733154950136],
 [0.4915763135946622, 0.49009973242520066],
 [0.4934737281067556, 0.4911700316224763],
 [0.45004170141784822, 0.4439309170518122],
 [0.44974979149291078, 0.45390415957188029],
 [0.49545454545454548, 0.49472147895889079],
 [0.49572560467055882, 0.49540257844806618],
 [0.4970809007506255, 0.49525662855752856],
 [0.48592577147623017, 0.48182923862807103],
 [0.49941618015012512, 0.49569447822914131],
 [0.50177231025854874, 0.49408902943322791],
 [0.49952043369474564, 0.49009973242520066],
 [0.49916597164303589, 0.49618097786426663],
 [0.49441201000834029, 0.48489418632936027],
 [0.49222268557130944, 0.48980783264412553],
 [0.51057130942452045, 0.49929457552906836],
 [0.50112593828190155, 0.49379712965215278],
 [0.50383653044203502, 0.4979810265142301],
 [0.50112593828190155, 0.49549987837509124],
 [0.49701834862385319, 0.49253223060082707]]

In [84]:
def output_result(solver, hidden_layer,learning_method ):
    clf = MLPClassifier(solver=solver, hidden_layer_sizes=hidden_layer,
                        learning_rate=learning_method,max_iter = 400,random_state=1)
    clf.fit(x_train, y_train)    
    train_fited = clf.predict(x_train)
    train_confusion_matrix = confusion_matrix(y_train, train_fited)
    train_acc = (sum(np.diag(train_confusion_matrix))+0.0)/sum(sum(train_confusion_matrix))
    print 'on balanced data:'
    print 'training acc:'
    print train_acc
    print train_confusion_matrix
    #test
    test_predicted = clf.predict(x_test)
    test_confusion_matrix = confusion_matrix(y_test,test_predicted )
    test_acc = (sum(np.diag(test_confusion_matrix))+0.0)/sum(sum(test_confusion_matrix))
    print 'testing acc:'
    print test_acc
    print test_confusion_matrix
    
    return([train_acc,test_acc])

solver = 'adam'
learning_method = 'adaptive'
hidder_layers = [[5,5],[5,5,5],[5,5,5,5],[5,5,5,5,5],[5,5,5,5,5,5],
                 [10,10],[10,10,10],[10,10,10,10],[10,10,10,10,10],[10,10,10,10,10,10],
                 [15,15],[15,15,15],[15,15,15,15],[15,15,15,15,15],[15,15,15,15,15,15],
                 [20,20],[20,20,20],[20,20,20,20],[20,20,20,20,20],[20,20,20,20,20,20],]
acc_results = []
for hidden_layer in hidder_layers: 
    print hidden_layer 
    acc_results.append(output_result(solver, hidden_layer,learning_method  ))
acc_results

[5, 5]
on balanced data:
training acc:
0.496246872394
[[6669 1951  400  156  416]
 [2415 3802 2268  628  479]
 [ 743 2394 3963 1881  611]
 [ 358 1023 2410 3578 2223]
 [ 641  528  724 1911 5788]]
testing acc:
0.493018730236
[[2844  825  177   70  195]
 [1042 1581  982  297  209]
 [ 325  999 1679  818  290]
 [ 146  468 1059 1510  928]
 [ 302  210  269  810 2520]]
[5, 5, 5]
on balanced data:
training acc:
0.459132610509
[[6500 1933  855  224   80]
 [2639 3479 2548  729  197]
 [ 825 2386 3858 1831  692]
 [ 268  992 2692 2932 2708]
 [ 300  588 1412 2041 5251]]
testing acc:
0.456531257602
[[2779  807  361  111   53]
 [1094 1474 1138  305  100]
 [ 382  986 1672  789  282]
 [ 119  425 1211 1214 1142]
 [ 149  265  561  891 2245]]
[5, 5, 5, 5]
on balanced data:
training acc:
0.487656380317
[[6425 1983  500  212  472]
 [2236 3356 2694  850  456]
 [ 663 1990 4172 2236  531]
 [ 325  831 2440 4036 1960]
 [ 592  456  752 2393 5399]]
testing acc:
0.489856482608
[[2744  837  232  101  197]
 [ 958 1408 

[[0.49624687239366139, 0.49301873023595233],
 [0.45913261050875731, 0.45653125760155677],
 [0.48765638031693076, 0.48985648260763803],
 [0.40052126772310259, 0.40335684748236439],
 [0.42602168473728108, 0.42695207978594019],
 [0.49960383653044205, 0.49428362928727804],
 [0.49293160967472893, 0.49272683045487714],
 [0.49733110925771479, 0.49360252979810265],
 [0.4809841534612177, 0.47375334468499147],
 [0.49311926605504586, 0.48601313549014841],
 [0.50275229357798168, 0.49632692775480419],
 [0.50448290241868221, 0.49301873023595233],
 [0.50304420350291912, 0.49593772804670394],
 [0.4926814011676397, 0.49058623206032598],
 [0.50675562969140953, 0.49982972512770618],
 [0.50752710592160133, 0.4995864753101435],
 [0.50425354462051708, 0.49973242520068112],
 [0.50796497080900749, 0.49287278034541476],
 [0.49718515429524601, 0.4915592313305765],
 [0.4971017514595496, 0.4867915349063488]]